name: Dev Deploy to GCP - GKE

env: 
  IMAGE_NAME: conductor-oss
  CONDUCTOR_VERSION: 3.21.3
  PROJECT_ID: vt-next-generation-346622
  GAR_LOCATION: us-east1 
  REPOSITORY: conductor-server

on:
  push:
    branches:
    - main

jobs:
  setup-build-publish-deploy:
    name: Dev test and Push 
    runs-on: ubuntu-latest
    environment: development

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set env
      run: echo "COMMIT_COUNT_TAG=$(git rev-list HEAD | wc -l | sed 's/^ *//g')" >> $GITHUB_ENV

    - name: Test env
      run: echo $COMMIT_COUNT_TAG  

    - id: 'auth'
      uses: 'google-github-actions/auth@v0.6.0'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
        token_format: 'access_token'     

    - uses: 'docker/login-action@v1'
      name: 'Docker login'
      with:
        registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$CONDUCTOR_VERSION.${{env.COMMIT_COUNT_TAG}}" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          -f docker/server/Dockerfile \
          --progress=plain \
          .

    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$CONDUCTOR_VERSION.${{env.COMMIT_COUNT_TAG}}"
